AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: arXiv pipeline infra

Parameters:
  BucketName:
    Type: String
  TableName:
    Type: String
    Default: arxiv_ingest_status

Resources:
  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  IngestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: arxiv_id
          AttributeType: S
      KeySchema:
        - AttributeName: arxiv_id
          KeyType: HASH

  FetchLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: lambda_handlers/fetch_handler.lambda_handler
      Runtime: python3.11
      Timeout: 120
      MemorySize: 256
      Environment:
        Variables:
          RAW_BUCKET: !Ref BucketName
          TABLE_NAME: !Ref TableName
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)

  TransformLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: lambda_handlers/transform_handler.lambda_handler
      Runtime: python3.11
      Timeout: 180
      MemorySize: 512
      Environment:
        Variables:
          RAW_BUCKET: !Ref BucketName
          TABLE_NAME: !Ref TableName
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
        - S3WritePolicy:
            BucketName: !Ref BucketName
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref RawBucket
            Events: s3:ObjectCreated:*

Outputs:
  BucketName:
    Value: !Ref BucketName
  TableName:
    Value: !Ref TableName
